package org.apache.spark.sql

import org.apache.spark.connect.proto.{Expression, Relation}

/** A Column subtype representing a CASE WHEN chain.
  *
  * Instances are produced only by `functions.when(cond, value)` and subsequent chained `.when(...)`
  * / `.otherwise(...)` calls on a `WhenColumn`. The dedicated type (rather than string matching the
  * function name) prevents invalid chains such as `col.alias("x").when(...)` or a
  * `callFn("when", ...)`-constructed Column from being silently accepted.
  *
  * The underlying proto is still an `UnresolvedFunction("when", args)` where args are
  * `(cond1, val1, cond2, val2, ..., [otherwise])`.
  *
  * '''Design invariant''': Any `Column` operation that returns a plain `Column` (e.g. `alias`,
  * `cast`, `as`, comparison operators) MUST lose the `WhenColumn` type. The `final` modifier and
  * the fact that `Column.withExpr` / `Column.as` construct `Column(...)` directly keep this
  * invariant. Adding `WhenColumn`-returning overrides for `alias`/`cast`/`withExpr` would silently
  * re-enable the exact edge cases this class was introduced to reject.
  */
final private[sql] class WhenColumn private[sql] (
    private val branches: Seq[(Expression, Expression)],
    private val otherwiseExpr: Option[Expression],
    inheritedSubqueryRelations: Seq[Relation]
) extends Column(
      WhenColumn.buildExpr(branches, otherwiseExpr),
      inheritedSubqueryRelations
    ):

  override def when(condition: Column, value: Any): Column =
    if otherwiseExpr.isDefined then
      throw IllegalArgumentException(
        "when() cannot be applied once otherwise() is applied"
      )
    val v = WhenColumn.asColumn(value)
    new WhenColumn(
      branches :+ (condition.expr -> v.expr),
      None,
      subqueryRelations ++ condition.subqueryRelations ++ v.subqueryRelations
    )

  override def otherwise(value: Any): Column =
    if otherwiseExpr.isDefined then
      throw IllegalArgumentException(
        "otherwise() can only be applied once on a Column previously generated by when()"
      )
    val v = WhenColumn.asColumn(value)
    new WhenColumn(
      branches,
      Some(v.expr),
      subqueryRelations ++ v.subqueryRelations
    )

private[sql] object WhenColumn:

  def apply(condition: Column, value: Any): WhenColumn =
    val v = asColumn(value)
    new WhenColumn(
      Seq(condition.expr -> v.expr),
      None,
      condition.subqueryRelations ++ v.subqueryRelations
    )

  private def asColumn(value: Any): Column = value match
    case null      => Column.lit(null)
    case c: Column => c
    case other     => Column.lit(other)

  private def buildExpr(
      branches: Seq[(Expression, Expression)],
      otherwiseExpr: Option[Expression]
  ): Expression =
    val uf = Expression.UnresolvedFunction.newBuilder().setFunctionName("when")
    branches.foreach: (cond, v) =>
      uf.addArguments(cond)
      uf.addArguments(v)
    otherwiseExpr.foreach(uf.addArguments)
    Expression.newBuilder().setUnresolvedFunction(uf.build()).build()
