package org.apache.spark.sql

import org.apache.spark.connect.proto.{Expression, Relation}

/** A Column subtype representing a CASE WHEN chain.
  *
  * Instances are produced only by `functions.when(cond, value)` and subsequent chained
  * `.when(...)` / `.otherwise(...)` calls on a `WhenColumn`. The dedicated type (rather than
  * string matching the function name) prevents invalid chains such as
  * `col.alias("x").when(...)` or `callFn("when", ...).when(...)` from being silently accepted.
  *
  * The underlying proto is still an `UnresolvedFunction("when", args)` where args are
  * `(cond1, val1, cond2, val2, ..., [otherwise])`.
  */
private[sql] final class WhenColumn private[sql] (
    private val branches: Seq[(Expression, Expression)],
    private val otherwiseExpr: Option[Expression],
    subqueryRelationsIn: Seq[Relation]
) extends Column(
      WhenColumn.buildExpr(branches, otherwiseExpr),
      subqueryRelationsIn
    ):

  override def when(condition: Column, value: Any): Column =
    if otherwiseExpr.isDefined then
      throw IllegalArgumentException(
        "when() cannot be applied after otherwise() has been called"
      )
    val v = WhenColumn.asColumn(value)
    new WhenColumn(
      branches :+ (condition.expr -> v.expr),
      None,
      subqueryRelations ++ condition.subqueryRelations ++ v.subqueryRelations
    )

  override def otherwise(value: Any): Column =
    if otherwiseExpr.isDefined then
      throw IllegalArgumentException(
        "otherwise() can only be applied once on a Column previously generated by when()"
      )
    val v = WhenColumn.asColumn(value)
    new WhenColumn(
      branches,
      Some(v.expr),
      subqueryRelations ++ v.subqueryRelations
    )

private[sql] object WhenColumn:

  def apply(condition: Column, value: Any): WhenColumn =
    val v = asColumn(value)
    new WhenColumn(
      Seq(condition.expr -> v.expr),
      None,
      condition.subqueryRelations ++ v.subqueryRelations
    )

  private def asColumn(value: Any): Column = value match
    case c: Column => c
    case other     => Column.lit(other)

  private def buildExpr(
      branches: Seq[(Expression, Expression)],
      otherwiseExpr: Option[Expression]
  ): Expression =
    val uf = Expression.UnresolvedFunction.newBuilder().setFunctionName("when")
    branches.foreach: (cond, v) =>
      uf.addArguments(cond)
      uf.addArguments(v)
    otherwiseExpr.foreach(uf.addArguments)
    Expression.newBuilder().setUnresolvedFunction(uf.build()).build()
